name: Tests

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: warbler-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.7.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.7.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest bs4
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the tests
        run: |
          export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/warbler-test"
          pytest
